### ISSUE TITLE
[1.5.1] compile error

### ISSUE THREAD

**Issue by LayYuan** [2d-inc/Flare-Flutter#98] opened 2019-06-07 09:07 UTC
First time try to use flare. As in pub.dev suggest to use flare_flutter 1.5.1
But it fail to build.

Compiler message:
file:///Users/macb/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.1/lib/flare.dart:1023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.

**Comment by jmeinlschmidt** [comment] 2019-06-07 12:44
Probably caused by new flutter version. Could be temporarily fixed by downgrading flutter `flutter version <version>`

**Comment by jmeinlschmidt** [comment] 2019-06-07 12:45
duplicate [#96](https://github.com/2d-inc/Flare-Flutter/issues/96)

**Comment by luigi-rosso** [comment] 2019-06-08 19:10
Make sure you use the corresponding flutter channel with the Flare-Flutter branch. Use pub only if you are on flutter stable. It seems like you are on another flutter channel (maybe dev or master).

**Closed** 2019-06-12 11:06 UTC
