### ISSUE TITLE
The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.  - 'Int32List' is from 'dart:typed_data'.  - 'Uint16List' is from 'dart:typed_data'. Try changing the type of the parameter, or casting the argument to 'Uint16List'.         indices: _indices, textureCoordinates: _uvBuffer);

### ISSUE THREAD

**Issue by jinfagang** [2d-inc/Flare-Flutter#105] opened 2019-06-18 15:24 UTC
The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);

**Comment by umberto-sonnino** [comment] 2019-06-18 15:52
This might be a duplicate of #96 and #98 
Have you tried [this](https://github.com/2d-inc/Flare-Flutter/issues/96#issuecomment-497696424) approach?

**Closed** 2019-06-18 15:56 UTC
Labels: duplicate
