### ISSUE TITLE
Migration to Null-Safety

### ISSUE THREAD

**Issue by deimantasa** [2d-inc/Flare-Flutter#294] opened 2021-03-07 03:49 UTC
Hello team,

Is there any ETA for migration to be done?

Cheers

**Comment by deimantasa** [comment] 2021-03-10 12:11
Seems that something is in works https://github.com/2d-inc/Flare-Flutter/pull/293

**Comment by mjohnsullivan** [comment] 2021-03-11 19:16
Our plan is to work on this in earnest next week to get a release out shortly.

**Comment by mjohnsullivan** [comment] 2021-03-11 19:18
Duplicate of #291

**Closed as completed by mjohnsullivan** 2021-03-11 19:18 UTC
