### ISSUE TITLE
Incompatibility with Dart 2.1

### ISSUE THREAD

**Issue by nahuelcabrera** [2d-inc/Flare-Flutter#3] opened 2018-12-05 01:32 UTC
Failed to get the Flare dependencies because they do not run with Dart 2.1

**Comment by mploigt** [comment] 2018-12-05 07:56
Same here

**Comment by awazgyawali** [comment] 2018-12-05 14:36
Weird to see this happening, coz it was just announced yesterday.

**Comment by munukutla** [comment] 2018-12-05 17:53
@luigi-rosso, any idea why this happens?

**Comment by munukutla** [comment] 2018-12-05 19:18
Yeah, even the example project on the repo does the same - it doesn't import `flare` from pub. True, it's a work around, but gets messy once you need to put your project on a CI system.

Hope the guys fix it soon.

**Comment by luigi-rosso** [comment] 2018-12-05 19:30
Sorry everyone, we’re still traveling back from London for the next few days so we’re not quite as responsive as we usually are. I will fix this issue tonight, however. Will write back later. Thanks for the excitement in trying this out so quickly.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by munukutla** [comment] 2018-12-05 20:03
@luigi-rosso No issues mate. You’ve done a great job at Flutter Live to be honest. Bonus tolerance for you guys until you fix this. 

Looking forward to start using Flare and Nima.

**Comment by luigi-rosso** [comment] 2018-12-06 00:59
I think the problem is that everyone is trying to use the "flare" dependency from Dart Pub. This is a bug in our readme. In the excitement we actually forgot to publish a package. We've been referencing the Flare library as a submodule and adding the dependency via a path reference to the your pubspec.yaml. I'm publishing a package now and updating the documentation to reflect the correct package name (unfortunately flare is already in use). More updates soon!

**Comment by luigi-rosso** [comment] 2018-12-07 20:11
Closing this, feel free to re-open if you run into any problems.

**Closed by luigi-rosso** 2018-12-07 20:11 UTC
